---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1665670/public_html/fashafadillah.xyz/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp writing.html $DEPLOYPATH
    - /bin/cp footer.css $DEPLOYPATH
    - /bin/cp home.css $DEPLOYPATH
    - /bin/cp navbar.css $DEPLOYPATH
    - /bin/cp root.css $DEPLOYPATH
    - /bin/cp writing.css $DEPLOYPATH
    - /bin/cp script.js $DEPLOYPATH
    - /bin/cp activePage.js $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R writing $DEPLOYPATH
